version: "3"

networks:
  nw-api-example: 
    driver: bridge
  nw-redis:
    driver: bridge
  nw-rabbitmq:
    driver: bridge

services:
  nginx: 
    build: 
      context: ./nginx
    networks:
      - nw-redis
      - nw-rabbitmq
      - nw-api-example
    hostname: nginx
    container_name: nginx-reverse-proxy
    ports: 
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - redis
      - rabbitmq
      - api-example

  redis: 
    image: redis:alpine
    container_name: redis
    hostname: redis.local
    networks:
      - nw-redis
    ports: 
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass "redis123"
    volumes:
      - ./redis/data:/data
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq.local
    networks:
      - nw-rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor

  api-example: 
    build: 
      context: ../backend/sources
    container_name: api-example
    hostname: api.example.local
    networks:
      - nw-api-example
      - nw-rabbitmq
      - nw-redis
    ports: 
      - "4100:4100"
    volumes:
      - ../backend/sources:/usr/src/app
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis
      - rabbitmq

  # zookeeper:
  #   image: 'zookeeper'
  #   restart: always
  #   hostname: zookeeper
  #   container_name: kabgo-zookeeper
  #   ports:
  #     - 2181:2181
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - FORCE_COLOR=1
  #     - DEBUG_COLORS="true"
  #     - TERM=xterm-256color
  #     - COLORTERM=truecolor

  # kafka:
  #   image: 'bitnami/kafka'
  #   hostname: kafka.kabgo.local
  #   container_name: kabgo-kafka
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_CFG_BROKER_ID=1
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
  #     - FORCE_COLOR=1
  #     - DEBUG_COLORS="true"
  #     - TERM=xterm-256color
  #     - COLORTERM=truecolor
  #   depends_on: 
  #     - zookeeper
